import Image from "next/image";
import { ArrowDown, ArrowUpRight, Award, ExternalLink, GitBranch, BriefcaseBusiness, Mail, MapPin, Sparkles } from "lucide-react";
import { profile, pillars, projects, skills, education, certificates } from "@/data/portfolioData";
import { Navbar } from "@/components/Navbar";
import { Contact } from "@/components/Contact";
import { AnimatedSection } from "@/components/ui/AnimatedSection";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { SocialIcon } from "@/components/ui/SocialIcon";

export default function Home() {
  return (
    <>
      <Navbar />
      <main className="bg-slate-50 dark:bg-gray-900">
        <section id="home" className="mx-auto grid min-h-screen max-w-6xl scroll-mt-24 items-center gap-12 bg-slate-50 px-4 pb-16 pt-28 dark:bg-gray-900 sm:gap-16 sm:px-6 sm:pb-20 sm:pt-32 lg:grid-cols-[1.05fr_.95fr] lg:gap-20">
          <div className="text-center lg:text-left">
            <h1 className="text-5xl font-extrabold leading-[1.05] tracking-tight text-black sm:text-7xl dark:text-white">Hello I&apos;m<br /><span className="text-sky-500">Indra Wahyu</span>{" "}<span className="text-green-500">Santoso</span></h1>
            <p className="mx-auto mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300 lg:mx-0">{profile.shortBioEn}</p>
            <div className="mt-5 flex flex-wrap items-center justify-center gap-6 text-sm text-slate-600 dark:text-slate-300 lg:justify-start"><span className="flex items-center gap-2"><Mail size={16} />{profile.email}</span><span className="flex items-center gap-2"><MapPin size={16} />{profile.location}</span></div>
            <div className="mt-8 flex flex-wrap justify-center gap-4 lg:justify-start"><Button href="#projects" variant="green">View My Work <ArrowDown size={16} /></Button><Button href={profile.cvUrl} variant="outline" external download>Download CV <ArrowUpRight size={16} /></Button></div>
            <div className="mt-8 flex justify-center gap-3 lg:justify-start"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="on-accent flex h-12 w-12 items-center justify-center rounded-brutal border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="github" /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="on-accent flex h-12 w-12 items-center justify-center rounded-brutal border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="linkedin" /></a><a href={`mailto:${profile.email}`} aria-label="Email" className="on-accent flex h-12 w-12 items-center justify-center rounded-brutal border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="email" /></a></div>
          </div>
          <div className="mx-auto w-full max-w-sm lg:max-w-xs"><div className="relative rounded-brutal border-4 border-black bg-transparent p-0 shadow-brutal-lg"><div className="relative flex aspect-square items-center justify-center overflow-hidden rounded-brutal bg-transparent"><Image src="/Indra_Wahyu_Santoso.png" alt="Foto Indra Wahyu Santoso" fill sizes="(max-width: 1024px) 90vw, 320px" className="object-cover object-top" priority /></div><div className="on-accent absolute -bottom-3 -left-3 border-hard bg-fuchsia-400 p-3 text-black shadow-brutal-sm sm:-bottom-5 sm:-left-5"><Sparkles size={24} /></div><div className="on-accent absolute -right-3 -top-3 border-hard bg-green-300 p-3 text-black shadow-brutal-sm sm:-right-5 sm:-top-5"><Sparkles size={20} /></div></div></div>
        </section>

        <AnimatedSection id="about" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-28"><SectionHeading number="01" title="About | Me" align="left" /><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="whitespace-pre-line text-[15px] leading-8 text-slate-600 dark:text-slate-300">{profile.about}<div className="mt-8 flex flex-wrap gap-3"><Badge>🎓 Informatika · UBSI</Badge><Badge>📍 {profile.location}</Badge><Badge variant="green">💼 Available</Badge></div></div><div className="grid grid-cols-1 gap-5 self-start sm:grid-cols-2">{pillars.map((p) => { const Icon = p.icon; return <div key={p.title} className="border-hard bg-white p-5 shadow-brutal-sm dark:bg-gray-800"><div style={{ backgroundColor: p.color }} className="on-accent mb-5 inline-flex rounded-brutal border-2 border-black p-3 text-black"><Icon size={20} /></div><h3 className="font-extrabold text-black dark:text-white">{p.title}</h3></div>; })}</div></div></AnimatedSection>

        <AnimatedSection id="skills" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-28"><SectionHeading number="02" title="Skills">Teknologi yang sedang saya pelajari dan gunakan dalam berbagai proyek.</SectionHeading><div className="mx-auto grid max-w-4xl grid-cols-2 gap-5 sm:grid-cols-4">{skills.map((skill) => { const Icon = skill.icon; return <div key={skill.name} className="group overflow-hidden border-hard bg-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none dark:bg-gray-800"><div style={{ backgroundColor: skill.color }} className="on-accent flex h-20 items-center justify-center border-b-2 border-black text-black"><Icon size={34} className="transition-transform duration-300 group-hover:scale-110" /></div><div className="p-3"><h3 className="text-sm font-extrabold text-black dark:text-white">{skill.name}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{skill.category}</p></div></div>; })}</div></AnimatedSection>

        <AnimatedSection id="projects" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-28"><SectionHeading number="03" title="Projects">Proyek akademik dan mandiri yang saya kerjakan untuk terus berkembang.</SectionHeading><div className="grid gap-8 md:grid-cols-2">{projects.map((project) => <article key={project.title} className="group overflow-hidden border-hard bg-white shadow-brutal dark:bg-gray-800"><div className="on-accent flex h-52 items-center justify-center border-b-[3px] border-black bg-gradient-to-br from-fuchsia-500 to-sky-500"><span className="text-3xl font-extrabold text-white transition-transform duration-300 group-hover:scale-110">{project.title}</span></div><div style={{ backgroundColor: project.accentColor }} className="on-accent border-b-[3px] border-black px-5 py-4"><h3 className="text-xl font-extrabold text-black">{project.title}</h3></div><div className="p-6"><p className="text-sm leading-7 text-slate-600 dark:text-slate-300">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((tech) => <Badge key={tech}>{tech}</Badge>)}</div><a href={project.github} target="_blank" rel="noreferrer" className="mono mt-6 inline-flex items-center gap-2 rounded-brutal border-2 border-black bg-black dark:bg-gray-100 dark:text-black px-4 py-2 text-xs font-bold text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none">Code <ExternalLink size={15} /></a></div></article>)}</div></AnimatedSection>

        <AnimatedSection id="education" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-28"><SectionHeading number="04" title="Education | Journey" /><div className="mx-auto max-w-3xl space-y-8 border-hard bg-white p-7 shadow-brutal-sm dark:bg-gray-800">{education.map((item) => <div key={item.institution} className="border-l-4 border-black pl-5"><h3 className="text-lg font-extrabold text-black dark:text-white">{item.institution}</h3><p className="mt-2 text-slate-600 dark:text-slate-300">{item.program}</p><p className="mono mt-3 text-xs text-slate-500 dark:text-slate-400">{item.period}</p></div>)}</div></AnimatedSection>

        <AnimatedSection id="certificates" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-28"><SectionHeading number="05" title="Certificates">Sertifikasi dan pelatihan yang memperkuat kompetensi teknis saya.</SectionHeading><div className="grid gap-8 md:grid-cols-2">{certificates.map((certificate) => <article key={certificate.title} className="overflow-hidden border-hard bg-white shadow-brutal dark:bg-gray-800"><div style={{ backgroundColor: certificate.accentColor }} className="on-accent border-b-[3px] border-black px-5 py-4"><h3 className="text-lg font-extrabold text-black">{certificate.title}</h3></div><div className="p-6"><a href={certificate.image} target="_blank" rel="noreferrer" aria-label={`Buka sertifikat ${certificate.title}`} className="group block rounded-brutal border-2 border-black bg-slate-100 p-2 transition hover:translate-x-1 hover:translate-y-1 dark:bg-gray-700">{certificate.thumbnail ? <div className="relative h-56 w-full overflow-hidden rounded-brutal border-2 border-black bg-white"><Image src={certificate.thumbnail} alt={`Pratinjau sertifikat ${certificate.title}`} fill sizes="(max-width: 768px) 90vw, 380px" className="object-cover object-top transition-transform duration-300 group-hover:scale-105" /></div> : <div style={{ backgroundColor: certificate.accentColor }} className="on-accent flex h-56 w-full flex-col items-center justify-center gap-3 rounded-brutal border-2 border-black px-5 text-center text-black"><Award size={44} className="transition-transform duration-300 group-hover:scale-110" /><span className="mono line-clamp-2 text-[11px] font-bold uppercase leading-4 tracking-widest">{certificate.issuer}</span><span className="on-accent mono rounded-full border-2 border-black bg-white px-3 py-1 text-[10px] font-bold">BUKA PDF</span></div>}</a><div className="mt-5 flex flex-col gap-2 text-xs"><span className="mono text-slate-600 dark:text-slate-300">Penyelenggara: {certificate.issuer}</span><span className="mono text-slate-500 dark:text-slate-400">Tanggal: {certificate.date}</span></div>{certificate.description && <p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{certificate.description}</p>}<div className="mt-5 flex flex-wrap gap-2">{certificate.skills.map((skill) => <Badge key={skill}>{skill}</Badge>)}</div><a href={certificate.image} target="_blank" rel="noreferrer" className="mono mt-6 inline-flex w-full items-center justify-center gap-2 rounded-brutal border-2 border-black bg-black dark:bg-gray-100 dark:text-black px-4 py-3 text-xs font-bold text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none">Lihat Sertifikat <ArrowUpRight size={15} /></a></div></article>)}</div></AnimatedSection>
        <Contact />
      </main>
      <footer className="border-t-[3px] border-black bg-black text-white"><div className="mx-auto flex max-w-6xl flex-col items-center justify-center gap-6 px-4 py-10 sm:px-6"><div className="flex gap-3"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="rounded-brutal border-2 border-white p-2 transition hover:-translate-y-0.5"><GitBranch size={17} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="rounded-brutal border-2 border-white p-2 transition hover:-translate-y-0.5"><BriefcaseBusiness size={17} /></a></div><p className="mono text-xs text-slate-400">© {new Date().getFullYear()} {profile.name}</p></div></footer>
    </>
  );
}
