import Image from "next/image";
import { ArrowDown, ArrowUpRight, ExternalLink, GitBranch, BriefcaseBusiness, Mail, MapPin, Sparkles } from "lucide-react";
import { profile, pillars, projects, skills, education, certificates } from "@/data/portfolioData";
import { Navbar } from "@/components/Navbar";
import { Contact } from "@/components/Contact";
import { AnimatedSection } from "@/components/ui/AnimatedSection";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { SocialIcon } from "@/components/ui/SocialIcon";

export default function Home() {
  return (
    <>
      <Navbar />
      <main className="bg-slate-50 dark:bg-gray-900">
        <section id="home" className="mx-auto grid min-h-screen max-w-6xl items-center gap-16 bg-slate-50 px-4 pb-20 pt-32 dark:bg-gray-900 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:gap-20">
          <div className="text-center lg:text-left">
            <span className="mono inline-block border-2 border-black bg-green-300 px-4 py-2 text-xs font-bold tracking-wide text-black shadow-brutal-sm">{profile.heroBadge}</span>
            <h1 className="mono mt-6 text-5xl font-extrabold leading-[1.05] tracking-tight text-black sm:text-7xl dark:text-white">Hello I&apos;m<br /><span className="text-sky-500">Indra Wahyu</span>{" "}<span className="text-green-500">Santoso</span></h1>
            <p className="mx-auto mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300 lg:mx-0">{profile.shortBioEn}</p>
            <div className="mt-5 flex flex-wrap items-center justify-center gap-6 text-sm text-slate-600 dark:text-slate-300 lg:justify-start"><span className="flex items-center gap-2"><Mail size={16} />{profile.email}</span><span className="flex items-center gap-2"><MapPin size={16} />{profile.location}</span></div>
            <div className="mt-8 flex flex-wrap justify-center gap-4 lg:justify-start"><Button href="#projects" variant="green">View My Work <ArrowDown size={16} /></Button><Button href={profile.cvUrl} variant="outline" external>Download CV <ArrowUpRight size={16} /></Button></div>
            <div className="mt-8 flex justify-center gap-3 lg:justify-start"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="flex h-12 w-12 items-center justify-center border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="github" /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="flex h-12 w-12 items-center justify-center border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="linkedin" /></a><a href={`mailto:${profile.email}`} aria-label="Email" className="flex h-12 w-12 items-center justify-center border-2 border-black bg-sky-500 text-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none"><SocialIcon name="email" /></a></div>
          </div>
          <div className="mx-auto w-full max-w-sm lg:max-w-md"><div className="relative border-4 border-black bg-transparent p-0 shadow-brutal"><div className="relative flex aspect-square items-center justify-center overflow-hidden bg-transparent"><Image src="/Indra_Wahyu_Santoso.png" alt="Foto Indra Wahyu Santoso" fill sizes="(max-width: 1024px) 90vw, 420px" className="object-cover object-top mix-blend-multiply" priority /></div><div className="absolute -bottom-5 -left-5 border-hard bg-fuchsia-400 p-3 shadow-brutal-sm"><Sparkles size={24} /></div><div className="absolute -right-5 -top-5 border-hard bg-green-300 p-3 shadow-brutal-sm"><Sparkles size={20} /></div></div></div>
        </section>

        <AnimatedSection id="about" className="mx-auto max-w-6xl px-4 py-28 sm:px-6"><SectionHeading eyebrow="01 / TENTANG SAYA" title="About | Me" align="left" /><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="whitespace-pre-line text-[15px] leading-8 text-slate-600 dark:text-slate-300">{profile.about}<div className="mt-8 flex flex-wrap gap-3"><Badge>🎓 Informatika · UBSI</Badge><Badge>📍 {profile.location}</Badge><Badge variant="green">💼 Available</Badge></div></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2">{pillars.map((p) => <div key={p.title} className="border-hard bg-white p-5 shadow-brutal-sm dark:bg-gray-800"><div style={{ backgroundColor: p.color }} className="mb-5 inline-flex border-2 border-black p-3"><Sparkles size={20} /></div><h3 className="mono font-extrabold text-black dark:text-white">{p.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{p.description}</p></div>)}</div></div></AnimatedSection>

        <AnimatedSection id="skills" className="mx-auto max-w-6xl px-4 py-28 sm:px-6"><SectionHeading eyebrow="02 / KEAHLIAN" title="Skills">Teknologi yang sedang saya pelajari dan gunakan dalam berbagai proyek.</SectionHeading><div className="mx-auto grid max-w-4xl grid-cols-2 gap-5 sm:grid-cols-4">{skills.map((skill) => { const Icon = skill.icon; return <div key={skill.name} className="border-hard bg-white shadow-brutal-sm transition hover:translate-x-1 hover:translate-y-1 hover:shadow-none dark:bg-gray-800"><div style={{ backgroundColor: skill.color }} className="flex h-20 items-center justify-center border-b-2 border-black text-black"><Icon size={34} /></div><div className="p-3"><h3 className="mono text-sm font-extrabold text-black dark:text-white">{skill.name}</h3><p className="mt-1 text-xs text-slate-500">{skill.category}</p></div></div>; })}</div></AnimatedSection>

        <AnimatedSection id="projects" className="mx-auto max-w-6xl px-4 py-28 sm:px-6"><SectionHeading eyebrow="03 / PROYEK" title="Projects">Proyek akademik dan mandiri yang saya kerjakan untuk terus berkembang.</SectionHeading><div className="grid gap-8 md:grid-cols-2">{projects.map((project) => <article key={project.title} className="border-hard bg-white shadow-brutal dark:bg-gray-800"><div className="flex h-52 items-center justify-center border-b-[3px] border-black bg-gradient-to-br from-sky-500 via-indigo-500 to-fuchsia-500"><span className="mono text-3xl font-extrabold text-white">{project.title}</span></div><div style={{ backgroundColor: project.accentColor }} className="border-b-[3px] border-black px-5 py-4"><h3 className="mono text-xl font-extrabold text-black">{project.title}</h3></div><div className="p-6"><p className="text-sm leading-7 text-slate-600 dark:text-slate-300">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((tech) => <Badge key={tech}>{tech}</Badge>)}</div><a href={project.github} target="_blank" rel="noreferrer" className="mono mt-6 inline-flex items-center gap-2 border-2 border-black bg-black px-4 py-2 text-xs font-bold text-white shadow-brutal-sm hover:translate-x-1 hover:translate-y-1 hover:shadow-none">Code <ExternalLink size={15} /></a></div></article>)}</div></AnimatedSection>

        <AnimatedSection id="education" className="mx-auto max-w-6xl px-4 py-28 sm:px-6"><SectionHeading eyebrow="04 / PENDIDIKAN & PENGALAMAN" title="Education | Journey" /><div className="grid gap-8 md:grid-cols-2"><div className="border-hard bg-white p-7 shadow-brutal-sm dark:bg-gray-800"><p className="mono text-xs font-bold text-green-700">PENDIDIKAN</p>{education.map((item) => <div key={item.institution} className="mt-6 border-l-4 border-black pl-5"><h3 className="mono text-lg font-extrabold text-black dark:text-white">{item.institution}</h3><p className="mt-2 text-slate-600 dark:text-slate-300">{item.program}</p><p className="mono mt-3 text-xs text-slate-500">{item.period}</p></div>)}</div><div className="border-hard bg-white p-7 shadow-brutal-sm dark:bg-gray-800"><p className="mono text-xs font-bold text-green-700">PENGALAMAN</p><p className="mt-6 leading-7 text-slate-600 dark:text-slate-300">Saat ini saya membangun pengalaman praktis melalui proyek perkuliahan dan mandiri berbasis web.</p><div className="mt-6 flex flex-wrap gap-2"><Badge>Frontend Development</Badge><Badge>Academic Projects</Badge></div></div></div></AnimatedSection>

        <AnimatedSection id="certificates" className="mx-auto max-w-6xl px-4 py-28 sm:px-6"><SectionHeading eyebrow="05 / SERTIFIKAT" title="Certificates">Sertifikasi dan pelatihan yang memperkuat kompetensi teknis saya.</SectionHeading><div className="grid gap-8 md:grid-cols-2">{certificates.map((certificate) => <article key={certificate.title} className="border-hard bg-white shadow-brutal dark:bg-gray-800"><div style={{ backgroundColor: certificate.accentColor }} className="border-b-[3px] border-black px-5 py-4"><h3 className="mono text-lg font-extrabold text-black">{certificate.title}</h3></div><div className="p-6"><a href={certificate.image} target="_blank" rel="noreferrer" aria-label={`Buka sertifikat ${certificate.title}`} className="group block border-2 border-black bg-slate-100 p-2 transition hover:translate-x-1 hover:translate-y-1 hover:shadow-brutal-sm"><iframe src={`${certificate.image}#toolbar=0&navpanes=0&scrollbar=0`} title={`Preview ${certificate.title}`} className="pointer-events-none h-56 w-full bg-white" /></a><div className="mt-5 flex flex-col gap-2 text-xs"><span className="mono text-slate-600 dark:text-slate-300">Penyelenggara: {certificate.issuer}</span><span className="mono text-slate-500">Tanggal: {certificate.date}</span></div>{certificate.description && <p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{certificate.description}</p>}<div className="mt-5 flex flex-wrap gap-2">{certificate.skills.map((skill) => <Badge key={skill}>{skill}</Badge>)}</div><a href={certificate.image} target="_blank" rel="noreferrer" className="mono mt-6 inline-flex w-full items-center justify-center gap-2 border-2 border-black bg-black px-4 py-3 text-xs font-bold text-white shadow-brutal-sm hover:translate-x-1 hover:translate-y-1 hover:shadow-none">Lihat Sertifikat <ArrowUpRight size={15} /></a></div></article>)}</div></AnimatedSection>
        <Contact />
      </main>
      <footer className="border-t-[3px] border-black bg-black text-white"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-4 py-10 sm:px-6 md:flex-row md:items-center md:justify-between"><div><p className="mono text-xl font-extrabold text-sky-400">INDRA WAHYU SANTOSO</p><p className="mono mt-2 text-xs text-slate-400">Mahasiswa Informatika · Frontend Developer</p></div><div className="flex gap-3"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="border-2 border-white p-2"><GitBranch size={17} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="border-2 border-white p-2"><BriefcaseBusiness size={17} /></a></div></div></footer>
    </>
  );
}
